version: '3'

services:
  filrouge-simple-api:
    build: simple_api
    ports:
      - "5002:5002"
    networks:
      - web
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
#   labels:
#     - traefik.enable=true
#     - traefik.http.routers.express_preprod.rule=Host(api-flask.fil-rouge.fr)
#     - traefik.http.routers.apache_prod.rule=Host(${URLEXPRESS})
#     - traefik.http.services.express_preprod.loadbalancer.server.port=4000
#     - traefik.http.routers.express_preprod.entrypoints=websecure
#     - traefik.http.routers.express_preprod.tls.certresolver=myresolver
#   restart: always


  filrouge-website:
    build: website
    ports:
      - "80:80"
    depends_on:
      - filrouge-simple-api
    networks:
      - web
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=${API_USERNAME}
      - PASSWORD=${API_PASSWORD}
      - IPADDRESS=${HOST_ADDRESS}
#   labels:
#     - traefik.enable=true
#     - traefik.http.routers.apache_prod.rule=Host(front-website.fil-rouge.fr)
#     - traefik.http.routers.apache_prod.rule=Host(${URLANGULAR})
#     - traefik.http.services.apache_prod.loadbalancer.server.port=80
#     - traefik.http.routers.apache_prod.entrypoints=websecure
#     - traefik.http.routers.apache_prod.tls.certresolver=myresolver
#   restart: always
networks:
  web:
    driver: bridge